version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    volumes:
      - ./clickhouse-config:/etc/clickhouse-server
      - clickhouse_data:/var/lib/clickhouse

  superset:
    build: ./superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
    depends_on:
      - clickhouse

  sales_data_gen:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: sales_data_gen
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:

