version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/etc/clickhouse-server/
      - clickhouse_data:/var/lib/clickhouse

  superset:
    build: ./superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:

