version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./clickhouse-config/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml:ro
      - ./data:/var/lib/clickhouse/user_files/data:ro
    restart: unless-stopped
    networks:
      - default_net

  superset:
    build: ./superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
    depends_on:
      - clickhouse
    networks:
      - default_net

  sales_data_gen:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: sales_data_gen
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse
    networks:
      - default_net

volumes:
  clickhouse_data:

networks:
  default_net:
    driver: bridge
